spring.application.name=quantitymeasurement

spring.datasource.url=jdbc:mysql://localhost:3306/quantitymeasurementdb
spring.datasource.username=root
spring.datasource.password=agam

spring.jpa.hibernate.ddl-auto=update